Fix deleting answer + support sortint by clicking on icon
evansendra/quora-upvotes pull request #3
Opened 2016-11-25 17:22 UTC by chao1995

In this pull request, there are three commits in total.

The first commit fixes the issue of adding the sort_btn onclick function multiple times. Actually, every time users click the dropdown to see "Sort by Upvotes", a new onclick function will be attached. This will cause problems because I guess (from some experiments) it will cause the on click functions to be invoked multiple times (and there is a problem in the original sort_question function, which will delete one answer at a time, thus causing deleting multiple answers).

The second commit fixes exactly the deleting one answer issue. It is in the for loop where we need to iterate from `i = 0` to` i < answers.length` (or` i <= answers.length - 1`), not  `i < answers.length - 1`.

The third commit adds a browser action to support sorting answers when users click on the icon. And a extra bonus is, the icon is now colourful! Yeah! :)

2016-11-25 21:14 UTC, evansendra commented
Thanks for the PR!  I'll check it out and review tomorrow or Sunday when I have time :)

2016-11-28 17:01 UTC, evansendra requested changes

2016-11-28 17:01 UTC, evansendra commented on js/upvotes.js
> +        console.log("quora upvotes: " + msg);
:+1:

2016-11-28 17:01 UTC, evansendra commented on js/upvotes.js
> +    // detach shown_answers from the answer list
I'm a fan of the other comments as they explain some tricky bits of code, but this one seems unnecessary to me; please remove

2016-11-28 17:01 UTC, evansendra commented on js/upvotes.js
> +    // convert shown_answers to array
unnecessary comment; please remove

2016-11-28 17:01 UTC, evansendra commented on manifest.json
> +    },
Per https://developer.chrome.com/extensions/event_pages#transition (see # 2 in that list), we shouldn't make this an event page until we switch to the alarms API.  I'd suggest removing from this PR if it's not critical to fixing #2 and then we can always fix in a future PR.

2016-11-28 17:01 UTC, evansendra commented on js/background.js
> +// Called when the user clicks on the browser action.
:+1:

2016-11-28 18:38 UTC, evansendra commented
Just a few minor changes to make, but this PR is really great.  A lot of code cleanup and bug fixes.  🙏

2016-11-29 07:40 UTC, chao1995 commented on js/upvotes.js
> +    // detach shown_answers from the answer list
Removed!

2016-11-29 07:40 UTC, chao1995 commented on js/upvotes.js
> +    // convert shown_answers to array
Removed!

2016-11-29 07:57 UTC, chao1995 commented on manifest.json
> +    },
I removed the third commit from this PR regarding to the background page.

Regarding the background page issue, I think by setting "persistent" to false, it is already an event page? And what `background.js` does is to add a listener for the icon-click event. So I think we don't need to use the alarms API?

2016-11-29 08:01 UTC, chao1995 commented
Just removed the unnecessary comments and the third commits.
It is really a better idea to not include non-related commits in one single PR.
Thank you very much for the review! :)

2016-11-29 22:38 UTC, evansendra approved these changes

2016-11-29 22:39 UTC, merged

2016-11-29 22:39 UTC, evansendra commented
closes #2